package com.yousoft.model.security;

import java.util.Date;

public class TSysresources {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sysresources.RESID
     *
     * @mbggenerated Tue Jun 02 21:20:20 CST 2015
     */
    private Integer resid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sysresources.RESNAME
     *
     * @mbggenerated Tue Jun 02 21:20:20 CST 2015
     */
    private String resname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sysresources.RESURL
     *
     * @mbggenerated Tue Jun 02 21:20:20 CST 2015
     */
    private String resurl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sysresources.COLUMN1
     *
     * @mbggenerated Tue Jun 02 21:20:20 CST 2015
     */
    private String column1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sysresources.COLUMN2
     *
     * @mbggenerated Tue Jun 02 21:20:20 CST 2015
     */
    private String column2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sysresources.COLUMN3
     *
     * @mbggenerated Tue Jun 02 21:20:20 CST 2015
     */
    private String column3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sysresources.CREATEUSER
     *
     * @mbggenerated Tue Jun 02 21:20:20 CST 2015
     */
    private Long createuser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sysresources.CREATETIME
     *
     * @mbggenerated Tue Jun 02 21:20:20 CST 2015
     */
    private Date createtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sysresources.UPDATERCODE
     *
     * @mbggenerated Tue Jun 02 21:20:20 CST 2015
     */
    private Long updatercode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sysresources.MODIFYTIME
     *
     * @mbggenerated Tue Jun 02 21:20:20 CST 2015
     */
    private Date modifytime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sysresources.VALID
     *
     * @mbggenerated Tue Jun 02 21:20:20 CST 2015
     */
    private Byte valid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sysresources.RESID
     *
     * @return the value of t_sysresources.RESID
     *
     * @mbggenerated Tue Jun 02 21:20:20 CST 2015
     */
    public Integer getResid() {
        return resid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sysresources.RESID
     *
     * @param resid the value for t_sysresources.RESID
     *
     * @mbggenerated Tue Jun 02 21:20:20 CST 2015
     */
    public void setResid(Integer resid) {
        this.resid = resid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sysresources.RESNAME
     *
     * @return the value of t_sysresources.RESNAME
     *
     * @mbggenerated Tue Jun 02 21:20:20 CST 2015
     */
    public String getResname() {
        return resname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sysresources.RESNAME
     *
     * @param resname the value for t_sysresources.RESNAME
     *
     * @mbggenerated Tue Jun 02 21:20:20 CST 2015
     */
    public void setResname(String resname) {
        this.resname = resname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sysresources.RESURL
     *
     * @return the value of t_sysresources.RESURL
     *
     * @mbggenerated Tue Jun 02 21:20:20 CST 2015
     */
    public String getResurl() {
        return resurl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sysresources.RESURL
     *
     * @param resurl the value for t_sysresources.RESURL
     *
     * @mbggenerated Tue Jun 02 21:20:20 CST 2015
     */
    public void setResurl(String resurl) {
        this.resurl = resurl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sysresources.COLUMN1
     *
     * @return the value of t_sysresources.COLUMN1
     *
     * @mbggenerated Tue Jun 02 21:20:20 CST 2015
     */
    public String getColumn1() {
        return column1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sysresources.COLUMN1
     *
     * @param column1 the value for t_sysresources.COLUMN1
     *
     * @mbggenerated Tue Jun 02 21:20:20 CST 2015
     */
    public void setColumn1(String column1) {
        this.column1 = column1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sysresources.COLUMN2
     *
     * @return the value of t_sysresources.COLUMN2
     *
     * @mbggenerated Tue Jun 02 21:20:20 CST 2015
     */
    public String getColumn2() {
        return column2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sysresources.COLUMN2
     *
     * @param column2 the value for t_sysresources.COLUMN2
     *
     * @mbggenerated Tue Jun 02 21:20:20 CST 2015
     */
    public void setColumn2(String column2) {
        this.column2 = column2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sysresources.COLUMN3
     *
     * @return the value of t_sysresources.COLUMN3
     *
     * @mbggenerated Tue Jun 02 21:20:20 CST 2015
     */
    public String getColumn3() {
        return column3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sysresources.COLUMN3
     *
     * @param column3 the value for t_sysresources.COLUMN3
     *
     * @mbggenerated Tue Jun 02 21:20:20 CST 2015
     */
    public void setColumn3(String column3) {
        this.column3 = column3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sysresources.CREATEUSER
     *
     * @return the value of t_sysresources.CREATEUSER
     *
     * @mbggenerated Tue Jun 02 21:20:20 CST 2015
     */
    public Long getCreateuser() {
        return createuser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sysresources.CREATEUSER
     *
     * @param createuser the value for t_sysresources.CREATEUSER
     *
     * @mbggenerated Tue Jun 02 21:20:20 CST 2015
     */
    public void setCreateuser(Long createuser) {
        this.createuser = createuser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sysresources.CREATETIME
     *
     * @return the value of t_sysresources.CREATETIME
     *
     * @mbggenerated Tue Jun 02 21:20:20 CST 2015
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sysresources.CREATETIME
     *
     * @param createtime the value for t_sysresources.CREATETIME
     *
     * @mbggenerated Tue Jun 02 21:20:20 CST 2015
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sysresources.UPDATERCODE
     *
     * @return the value of t_sysresources.UPDATERCODE
     *
     * @mbggenerated Tue Jun 02 21:20:20 CST 2015
     */
    public Long getUpdatercode() {
        return updatercode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sysresources.UPDATERCODE
     *
     * @param updatercode the value for t_sysresources.UPDATERCODE
     *
     * @mbggenerated Tue Jun 02 21:20:20 CST 2015
     */
    public void setUpdatercode(Long updatercode) {
        this.updatercode = updatercode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sysresources.MODIFYTIME
     *
     * @return the value of t_sysresources.MODIFYTIME
     *
     * @mbggenerated Tue Jun 02 21:20:20 CST 2015
     */
    public Date getModifytime() {
        return modifytime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sysresources.MODIFYTIME
     *
     * @param modifytime the value for t_sysresources.MODIFYTIME
     *
     * @mbggenerated Tue Jun 02 21:20:20 CST 2015
     */
    public void setModifytime(Date modifytime) {
        this.modifytime = modifytime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sysresources.VALID
     *
     * @return the value of t_sysresources.VALID
     *
     * @mbggenerated Tue Jun 02 21:20:20 CST 2015
     */
    public Byte getValid() {
        return valid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sysresources.VALID
     *
     * @param valid the value for t_sysresources.VALID
     *
     * @mbggenerated Tue Jun 02 21:20:20 CST 2015
     */
    public void setValid(Byte valid) {
        this.valid = valid;
    }
}