package com.yousoft.model.security;

import java.util.Date;

public class TSysuser {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sysuser.USERID
     *
     * @mbggenerated Tue Jun 02 21:20:20 CST 2015
     */
    private Long userid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sysuser.USERCODE
     *
     * @mbggenerated Tue Jun 02 21:20:20 CST 2015
     */
    private String usercode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sysuser.USERNAME
     *
     * @mbggenerated Tue Jun 02 21:20:20 CST 2015
     */
    private String username;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sysuser.DEPARTID
     *
     * @mbggenerated Tue Jun 02 21:20:20 CST 2015
     */
    private Integer departid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sysuser.EMAIL
     *
     * @mbggenerated Tue Jun 02 21:20:20 CST 2015
     */
    private String email;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sysuser.PHONENUMBER
     *
     * @mbggenerated Tue Jun 02 21:20:20 CST 2015
     */
    private String phonenumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sysuser.COLUMN1
     *
     * @mbggenerated Tue Jun 02 21:20:20 CST 2015
     */
    private String column1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sysuser.COLUMN2
     *
     * @mbggenerated Tue Jun 02 21:20:20 CST 2015
     */
    private String column2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sysuser.COLUMN3
     *
     * @mbggenerated Tue Jun 02 21:20:20 CST 2015
     */
    private String column3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sysuser.COLUMN4
     *
     * @mbggenerated Tue Jun 02 21:20:20 CST 2015
     */
    private String column4;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sysuser.COLUMN5
     *
     * @mbggenerated Tue Jun 02 21:20:20 CST 2015
     */
    private String column5;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sysuser.CREATEUSER
     *
     * @mbggenerated Tue Jun 02 21:20:20 CST 2015
     */
    private Long createuser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sysuser.CREATETIME
     *
     * @mbggenerated Tue Jun 02 21:20:20 CST 2015
     */
    private Date createtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sysuser.UPDATERCODE
     *
     * @mbggenerated Tue Jun 02 21:20:20 CST 2015
     */
    private Long updatercode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sysuser.MODIFYTIME
     *
     * @mbggenerated Tue Jun 02 21:20:20 CST 2015
     */
    private Date modifytime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sysuser.VALID
     *
     * @mbggenerated Tue Jun 02 21:20:20 CST 2015
     */
    private Byte valid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sysuser.USERID
     *
     * @return the value of t_sysuser.USERID
     *
     * @mbggenerated Tue Jun 02 21:20:20 CST 2015
     */
    public Long getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sysuser.USERID
     *
     * @param userid the value for t_sysuser.USERID
     *
     * @mbggenerated Tue Jun 02 21:20:20 CST 2015
     */
    public void setUserid(Long userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sysuser.USERCODE
     *
     * @return the value of t_sysuser.USERCODE
     *
     * @mbggenerated Tue Jun 02 21:20:20 CST 2015
     */
    public String getUsercode() {
        return usercode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sysuser.USERCODE
     *
     * @param usercode the value for t_sysuser.USERCODE
     *
     * @mbggenerated Tue Jun 02 21:20:20 CST 2015
     */
    public void setUsercode(String usercode) {
        this.usercode = usercode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sysuser.USERNAME
     *
     * @return the value of t_sysuser.USERNAME
     *
     * @mbggenerated Tue Jun 02 21:20:20 CST 2015
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sysuser.USERNAME
     *
     * @param username the value for t_sysuser.USERNAME
     *
     * @mbggenerated Tue Jun 02 21:20:20 CST 2015
     */
    public void setUsername(String username) {
        this.username = username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sysuser.DEPARTID
     *
     * @return the value of t_sysuser.DEPARTID
     *
     * @mbggenerated Tue Jun 02 21:20:20 CST 2015
     */
    public Integer getDepartid() {
        return departid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sysuser.DEPARTID
     *
     * @param departid the value for t_sysuser.DEPARTID
     *
     * @mbggenerated Tue Jun 02 21:20:20 CST 2015
     */
    public void setDepartid(Integer departid) {
        this.departid = departid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sysuser.EMAIL
     *
     * @return the value of t_sysuser.EMAIL
     *
     * @mbggenerated Tue Jun 02 21:20:20 CST 2015
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sysuser.EMAIL
     *
     * @param email the value for t_sysuser.EMAIL
     *
     * @mbggenerated Tue Jun 02 21:20:20 CST 2015
     */
    public void setEmail(String email) {
        this.email = email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sysuser.PHONENUMBER
     *
     * @return the value of t_sysuser.PHONENUMBER
     *
     * @mbggenerated Tue Jun 02 21:20:20 CST 2015
     */
    public String getPhonenumber() {
        return phonenumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sysuser.PHONENUMBER
     *
     * @param phonenumber the value for t_sysuser.PHONENUMBER
     *
     * @mbggenerated Tue Jun 02 21:20:20 CST 2015
     */
    public void setPhonenumber(String phonenumber) {
        this.phonenumber = phonenumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sysuser.COLUMN1
     *
     * @return the value of t_sysuser.COLUMN1
     *
     * @mbggenerated Tue Jun 02 21:20:20 CST 2015
     */
    public String getColumn1() {
        return column1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sysuser.COLUMN1
     *
     * @param column1 the value for t_sysuser.COLUMN1
     *
     * @mbggenerated Tue Jun 02 21:20:20 CST 2015
     */
    public void setColumn1(String column1) {
        this.column1 = column1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sysuser.COLUMN2
     *
     * @return the value of t_sysuser.COLUMN2
     *
     * @mbggenerated Tue Jun 02 21:20:20 CST 2015
     */
    public String getColumn2() {
        return column2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sysuser.COLUMN2
     *
     * @param column2 the value for t_sysuser.COLUMN2
     *
     * @mbggenerated Tue Jun 02 21:20:20 CST 2015
     */
    public void setColumn2(String column2) {
        this.column2 = column2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sysuser.COLUMN3
     *
     * @return the value of t_sysuser.COLUMN3
     *
     * @mbggenerated Tue Jun 02 21:20:20 CST 2015
     */
    public String getColumn3() {
        return column3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sysuser.COLUMN3
     *
     * @param column3 the value for t_sysuser.COLUMN3
     *
     * @mbggenerated Tue Jun 02 21:20:20 CST 2015
     */
    public void setColumn3(String column3) {
        this.column3 = column3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sysuser.COLUMN4
     *
     * @return the value of t_sysuser.COLUMN4
     *
     * @mbggenerated Tue Jun 02 21:20:20 CST 2015
     */
    public String getColumn4() {
        return column4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sysuser.COLUMN4
     *
     * @param column4 the value for t_sysuser.COLUMN4
     *
     * @mbggenerated Tue Jun 02 21:20:20 CST 2015
     */
    public void setColumn4(String column4) {
        this.column4 = column4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sysuser.COLUMN5
     *
     * @return the value of t_sysuser.COLUMN5
     *
     * @mbggenerated Tue Jun 02 21:20:20 CST 2015
     */
    public String getColumn5() {
        return column5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sysuser.COLUMN5
     *
     * @param column5 the value for t_sysuser.COLUMN5
     *
     * @mbggenerated Tue Jun 02 21:20:20 CST 2015
     */
    public void setColumn5(String column5) {
        this.column5 = column5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sysuser.CREATEUSER
     *
     * @return the value of t_sysuser.CREATEUSER
     *
     * @mbggenerated Tue Jun 02 21:20:20 CST 2015
     */
    public Long getCreateuser() {
        return createuser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sysuser.CREATEUSER
     *
     * @param createuser the value for t_sysuser.CREATEUSER
     *
     * @mbggenerated Tue Jun 02 21:20:20 CST 2015
     */
    public void setCreateuser(Long createuser) {
        this.createuser = createuser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sysuser.CREATETIME
     *
     * @return the value of t_sysuser.CREATETIME
     *
     * @mbggenerated Tue Jun 02 21:20:20 CST 2015
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sysuser.CREATETIME
     *
     * @param createtime the value for t_sysuser.CREATETIME
     *
     * @mbggenerated Tue Jun 02 21:20:20 CST 2015
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sysuser.UPDATERCODE
     *
     * @return the value of t_sysuser.UPDATERCODE
     *
     * @mbggenerated Tue Jun 02 21:20:20 CST 2015
     */
    public Long getUpdatercode() {
        return updatercode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sysuser.UPDATERCODE
     *
     * @param updatercode the value for t_sysuser.UPDATERCODE
     *
     * @mbggenerated Tue Jun 02 21:20:20 CST 2015
     */
    public void setUpdatercode(Long updatercode) {
        this.updatercode = updatercode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sysuser.MODIFYTIME
     *
     * @return the value of t_sysuser.MODIFYTIME
     *
     * @mbggenerated Tue Jun 02 21:20:20 CST 2015
     */
    public Date getModifytime() {
        return modifytime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sysuser.MODIFYTIME
     *
     * @param modifytime the value for t_sysuser.MODIFYTIME
     *
     * @mbggenerated Tue Jun 02 21:20:20 CST 2015
     */
    public void setModifytime(Date modifytime) {
        this.modifytime = modifytime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sysuser.VALID
     *
     * @return the value of t_sysuser.VALID
     *
     * @mbggenerated Tue Jun 02 21:20:20 CST 2015
     */
    public Byte getValid() {
        return valid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sysuser.VALID
     *
     * @param valid the value for t_sysuser.VALID
     *
     * @mbggenerated Tue Jun 02 21:20:20 CST 2015
     */
    public void setValid(Byte valid) {
        this.valid = valid;
    }
}