package com.yousoft.model.security;

import java.util.Date;

public class TSysuserrole {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sysuserrole.URID
     *
     * @mbggenerated Tue Jun 02 21:20:20 CST 2015
     */
    private Integer urid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sysuserrole.USERID
     *
     * @mbggenerated Tue Jun 02 21:20:20 CST 2015
     */
    private Long userid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sysuserrole.ROLEID
     *
     * @mbggenerated Tue Jun 02 21:20:20 CST 2015
     */
    private Integer roleid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sysuserrole.COLUMN1
     *
     * @mbggenerated Tue Jun 02 21:20:20 CST 2015
     */
    private String column1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sysuserrole.COLUMN2
     *
     * @mbggenerated Tue Jun 02 21:20:20 CST 2015
     */
    private String column2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sysuserrole.COLUMN3
     *
     * @mbggenerated Tue Jun 02 21:20:20 CST 2015
     */
    private String column3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sysuserrole.CREATEUSER
     *
     * @mbggenerated Tue Jun 02 21:20:20 CST 2015
     */
    private Long createuser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sysuserrole.CREATETIME
     *
     * @mbggenerated Tue Jun 02 21:20:20 CST 2015
     */
    private Date createtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sysuserrole.UPDATERCODE
     *
     * @mbggenerated Tue Jun 02 21:20:20 CST 2015
     */
    private Long updatercode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sysuserrole.MODIFYTIME
     *
     * @mbggenerated Tue Jun 02 21:20:20 CST 2015
     */
    private Date modifytime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sysuserrole.VALID
     *
     * @mbggenerated Tue Jun 02 21:20:20 CST 2015
     */
    private Byte valid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sysuserrole.URID
     *
     * @return the value of t_sysuserrole.URID
     *
     * @mbggenerated Tue Jun 02 21:20:20 CST 2015
     */
    public Integer getUrid() {
        return urid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sysuserrole.URID
     *
     * @param urid the value for t_sysuserrole.URID
     *
     * @mbggenerated Tue Jun 02 21:20:20 CST 2015
     */
    public void setUrid(Integer urid) {
        this.urid = urid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sysuserrole.USERID
     *
     * @return the value of t_sysuserrole.USERID
     *
     * @mbggenerated Tue Jun 02 21:20:20 CST 2015
     */
    public Long getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sysuserrole.USERID
     *
     * @param userid the value for t_sysuserrole.USERID
     *
     * @mbggenerated Tue Jun 02 21:20:20 CST 2015
     */
    public void setUserid(Long userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sysuserrole.ROLEID
     *
     * @return the value of t_sysuserrole.ROLEID
     *
     * @mbggenerated Tue Jun 02 21:20:20 CST 2015
     */
    public Integer getRoleid() {
        return roleid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sysuserrole.ROLEID
     *
     * @param roleid the value for t_sysuserrole.ROLEID
     *
     * @mbggenerated Tue Jun 02 21:20:20 CST 2015
     */
    public void setRoleid(Integer roleid) {
        this.roleid = roleid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sysuserrole.COLUMN1
     *
     * @return the value of t_sysuserrole.COLUMN1
     *
     * @mbggenerated Tue Jun 02 21:20:20 CST 2015
     */
    public String getColumn1() {
        return column1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sysuserrole.COLUMN1
     *
     * @param column1 the value for t_sysuserrole.COLUMN1
     *
     * @mbggenerated Tue Jun 02 21:20:20 CST 2015
     */
    public void setColumn1(String column1) {
        this.column1 = column1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sysuserrole.COLUMN2
     *
     * @return the value of t_sysuserrole.COLUMN2
     *
     * @mbggenerated Tue Jun 02 21:20:20 CST 2015
     */
    public String getColumn2() {
        return column2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sysuserrole.COLUMN2
     *
     * @param column2 the value for t_sysuserrole.COLUMN2
     *
     * @mbggenerated Tue Jun 02 21:20:20 CST 2015
     */
    public void setColumn2(String column2) {
        this.column2 = column2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sysuserrole.COLUMN3
     *
     * @return the value of t_sysuserrole.COLUMN3
     *
     * @mbggenerated Tue Jun 02 21:20:20 CST 2015
     */
    public String getColumn3() {
        return column3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sysuserrole.COLUMN3
     *
     * @param column3 the value for t_sysuserrole.COLUMN3
     *
     * @mbggenerated Tue Jun 02 21:20:20 CST 2015
     */
    public void setColumn3(String column3) {
        this.column3 = column3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sysuserrole.CREATEUSER
     *
     * @return the value of t_sysuserrole.CREATEUSER
     *
     * @mbggenerated Tue Jun 02 21:20:20 CST 2015
     */
    public Long getCreateuser() {
        return createuser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sysuserrole.CREATEUSER
     *
     * @param createuser the value for t_sysuserrole.CREATEUSER
     *
     * @mbggenerated Tue Jun 02 21:20:20 CST 2015
     */
    public void setCreateuser(Long createuser) {
        this.createuser = createuser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sysuserrole.CREATETIME
     *
     * @return the value of t_sysuserrole.CREATETIME
     *
     * @mbggenerated Tue Jun 02 21:20:20 CST 2015
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sysuserrole.CREATETIME
     *
     * @param createtime the value for t_sysuserrole.CREATETIME
     *
     * @mbggenerated Tue Jun 02 21:20:20 CST 2015
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sysuserrole.UPDATERCODE
     *
     * @return the value of t_sysuserrole.UPDATERCODE
     *
     * @mbggenerated Tue Jun 02 21:20:20 CST 2015
     */
    public Long getUpdatercode() {
        return updatercode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sysuserrole.UPDATERCODE
     *
     * @param updatercode the value for t_sysuserrole.UPDATERCODE
     *
     * @mbggenerated Tue Jun 02 21:20:20 CST 2015
     */
    public void setUpdatercode(Long updatercode) {
        this.updatercode = updatercode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sysuserrole.MODIFYTIME
     *
     * @return the value of t_sysuserrole.MODIFYTIME
     *
     * @mbggenerated Tue Jun 02 21:20:20 CST 2015
     */
    public Date getModifytime() {
        return modifytime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sysuserrole.MODIFYTIME
     *
     * @param modifytime the value for t_sysuserrole.MODIFYTIME
     *
     * @mbggenerated Tue Jun 02 21:20:20 CST 2015
     */
    public void setModifytime(Date modifytime) {
        this.modifytime = modifytime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sysuserrole.VALID
     *
     * @return the value of t_sysuserrole.VALID
     *
     * @mbggenerated Tue Jun 02 21:20:20 CST 2015
     */
    public Byte getValid() {
        return valid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sysuserrole.VALID
     *
     * @param valid the value for t_sysuserrole.VALID
     *
     * @mbggenerated Tue Jun 02 21:20:20 CST 2015
     */
    public void setValid(Byte valid) {
        this.valid = valid;
    }
}