package com.yousoft.model.security;

import java.util.Date;

public class TSysroleresource {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sysroleresource.ROLERESID
     *
     * @mbggenerated Tue Jun 02 21:20:20 CST 2015
     */
    private Integer roleresid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sysroleresource.ROLEID
     *
     * @mbggenerated Tue Jun 02 21:20:20 CST 2015
     */
    private Integer roleid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sysroleresource.RESID
     *
     * @mbggenerated Tue Jun 02 21:20:20 CST 2015
     */
    private Integer resid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sysroleresource.AUTHORITY
     *
     * @mbggenerated Tue Jun 02 21:20:20 CST 2015
     */
    private Integer authority;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sysroleresource.CREATEUSER
     *
     * @mbggenerated Tue Jun 02 21:20:20 CST 2015
     */
    private Long createuser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sysroleresource.CREATETIME
     *
     * @mbggenerated Tue Jun 02 21:20:20 CST 2015
     */
    private Date createtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sysroleresource.UPDATERCODE
     *
     * @mbggenerated Tue Jun 02 21:20:20 CST 2015
     */
    private Long updatercode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sysroleresource.MODIFYTIME
     *
     * @mbggenerated Tue Jun 02 21:20:20 CST 2015
     */
    private Date modifytime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sysroleresource.VALID
     *
     * @mbggenerated Tue Jun 02 21:20:20 CST 2015
     */
    private Byte valid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sysroleresource.ROLERESID
     *
     * @return the value of t_sysroleresource.ROLERESID
     *
     * @mbggenerated Tue Jun 02 21:20:20 CST 2015
     */
    public Integer getRoleresid() {
        return roleresid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sysroleresource.ROLERESID
     *
     * @param roleresid the value for t_sysroleresource.ROLERESID
     *
     * @mbggenerated Tue Jun 02 21:20:20 CST 2015
     */
    public void setRoleresid(Integer roleresid) {
        this.roleresid = roleresid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sysroleresource.ROLEID
     *
     * @return the value of t_sysroleresource.ROLEID
     *
     * @mbggenerated Tue Jun 02 21:20:20 CST 2015
     */
    public Integer getRoleid() {
        return roleid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sysroleresource.ROLEID
     *
     * @param roleid the value for t_sysroleresource.ROLEID
     *
     * @mbggenerated Tue Jun 02 21:20:20 CST 2015
     */
    public void setRoleid(Integer roleid) {
        this.roleid = roleid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sysroleresource.RESID
     *
     * @return the value of t_sysroleresource.RESID
     *
     * @mbggenerated Tue Jun 02 21:20:20 CST 2015
     */
    public Integer getResid() {
        return resid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sysroleresource.RESID
     *
     * @param resid the value for t_sysroleresource.RESID
     *
     * @mbggenerated Tue Jun 02 21:20:20 CST 2015
     */
    public void setResid(Integer resid) {
        this.resid = resid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sysroleresource.AUTHORITY
     *
     * @return the value of t_sysroleresource.AUTHORITY
     *
     * @mbggenerated Tue Jun 02 21:20:20 CST 2015
     */
    public Integer getAuthority() {
        return authority;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sysroleresource.AUTHORITY
     *
     * @param authority the value for t_sysroleresource.AUTHORITY
     *
     * @mbggenerated Tue Jun 02 21:20:20 CST 2015
     */
    public void setAuthority(Integer authority) {
        this.authority = authority;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sysroleresource.CREATEUSER
     *
     * @return the value of t_sysroleresource.CREATEUSER
     *
     * @mbggenerated Tue Jun 02 21:20:20 CST 2015
     */
    public Long getCreateuser() {
        return createuser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sysroleresource.CREATEUSER
     *
     * @param createuser the value for t_sysroleresource.CREATEUSER
     *
     * @mbggenerated Tue Jun 02 21:20:20 CST 2015
     */
    public void setCreateuser(Long createuser) {
        this.createuser = createuser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sysroleresource.CREATETIME
     *
     * @return the value of t_sysroleresource.CREATETIME
     *
     * @mbggenerated Tue Jun 02 21:20:20 CST 2015
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sysroleresource.CREATETIME
     *
     * @param createtime the value for t_sysroleresource.CREATETIME
     *
     * @mbggenerated Tue Jun 02 21:20:20 CST 2015
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sysroleresource.UPDATERCODE
     *
     * @return the value of t_sysroleresource.UPDATERCODE
     *
     * @mbggenerated Tue Jun 02 21:20:20 CST 2015
     */
    public Long getUpdatercode() {
        return updatercode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sysroleresource.UPDATERCODE
     *
     * @param updatercode the value for t_sysroleresource.UPDATERCODE
     *
     * @mbggenerated Tue Jun 02 21:20:20 CST 2015
     */
    public void setUpdatercode(Long updatercode) {
        this.updatercode = updatercode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sysroleresource.MODIFYTIME
     *
     * @return the value of t_sysroleresource.MODIFYTIME
     *
     * @mbggenerated Tue Jun 02 21:20:20 CST 2015
     */
    public Date getModifytime() {
        return modifytime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sysroleresource.MODIFYTIME
     *
     * @param modifytime the value for t_sysroleresource.MODIFYTIME
     *
     * @mbggenerated Tue Jun 02 21:20:20 CST 2015
     */
    public void setModifytime(Date modifytime) {
        this.modifytime = modifytime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sysroleresource.VALID
     *
     * @return the value of t_sysroleresource.VALID
     *
     * @mbggenerated Tue Jun 02 21:20:20 CST 2015
     */
    public Byte getValid() {
        return valid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sysroleresource.VALID
     *
     * @param valid the value for t_sysroleresource.VALID
     *
     * @mbggenerated Tue Jun 02 21:20:20 CST 2015
     */
    public void setValid(Byte valid) {
        this.valid = valid;
    }
}