package com.yousoft.model.security;

import java.util.Date;

public class TSysuserauth {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sysuserauth.AUID
     *
     * @mbggenerated Thu Jun 04 14:54:12 CST 2015
     */
    private Long auid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sysuserauth.USERID
     *
     * @mbggenerated Thu Jun 04 14:54:12 CST 2015
     */
    private Long userid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sysuserauth.LOGINCODE
     *
     * @mbggenerated Thu Jun 04 14:54:12 CST 2015
     */
    private String logincode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sysuserauth.PASSWORD
     *
     * @mbggenerated Thu Jun 04 14:54:12 CST 2015
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sysuserauth.STATUS
     *
     * @mbggenerated Thu Jun 04 14:54:12 CST 2015
     */
    private Byte status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sysuserauth.COLUMN1
     *
     * @mbggenerated Thu Jun 04 14:54:12 CST 2015
     */
    private String column1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sysuserauth.COLUMN2
     *
     * @mbggenerated Thu Jun 04 14:54:12 CST 2015
     */
    private String column2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sysuserauth.COLUMN3
     *
     * @mbggenerated Thu Jun 04 14:54:12 CST 2015
     */
    private String column3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sysuserauth.COLUMN4
     *
     * @mbggenerated Thu Jun 04 14:54:12 CST 2015
     */
    private String column4;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sysuserauth.COLUMN5
     *
     * @mbggenerated Thu Jun 04 14:54:12 CST 2015
     */
    private String column5;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sysuserauth.CREATEUSER
     *
     * @mbggenerated Thu Jun 04 14:54:12 CST 2015
     */
    private Long createuser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sysuserauth.CREATETIME
     *
     * @mbggenerated Thu Jun 04 14:54:12 CST 2015
     */
    private Date createtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sysuserauth.UPDATERCODE
     *
     * @mbggenerated Thu Jun 04 14:54:12 CST 2015
     */
    private Long updatercode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sysuserauth.MODIFYTIME
     *
     * @mbggenerated Thu Jun 04 14:54:12 CST 2015
     */
    private Date modifytime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sysuserauth.VALID
     *
     * @mbggenerated Thu Jun 04 14:54:12 CST 2015
     */
    private Byte valid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sysuserauth.AUID
     *
     * @return the value of t_sysuserauth.AUID
     *
     * @mbggenerated Thu Jun 04 14:54:12 CST 2015
     */
    public Long getAuid() {
        return auid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sysuserauth.AUID
     *
     * @param auid the value for t_sysuserauth.AUID
     *
     * @mbggenerated Thu Jun 04 14:54:12 CST 2015
     */
    public void setAuid(Long auid) {
        this.auid = auid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sysuserauth.USERID
     *
     * @return the value of t_sysuserauth.USERID
     *
     * @mbggenerated Thu Jun 04 14:54:12 CST 2015
     */
    public Long getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sysuserauth.USERID
     *
     * @param userid the value for t_sysuserauth.USERID
     *
     * @mbggenerated Thu Jun 04 14:54:12 CST 2015
     */
    public void setUserid(Long userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sysuserauth.LOGINCODE
     *
     * @return the value of t_sysuserauth.LOGINCODE
     *
     * @mbggenerated Thu Jun 04 14:54:12 CST 2015
     */
    public String getLogincode() {
        return logincode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sysuserauth.LOGINCODE
     *
     * @param logincode the value for t_sysuserauth.LOGINCODE
     *
     * @mbggenerated Thu Jun 04 14:54:12 CST 2015
     */
    public void setLogincode(String logincode) {
        this.logincode = logincode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sysuserauth.PASSWORD
     *
     * @return the value of t_sysuserauth.PASSWORD
     *
     * @mbggenerated Thu Jun 04 14:54:12 CST 2015
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sysuserauth.PASSWORD
     *
     * @param password the value for t_sysuserauth.PASSWORD
     *
     * @mbggenerated Thu Jun 04 14:54:12 CST 2015
     */
    public void setPassword(String password) {
        this.password = password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sysuserauth.STATUS
     *
     * @return the value of t_sysuserauth.STATUS
     *
     * @mbggenerated Thu Jun 04 14:54:12 CST 2015
     */
    public Byte getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sysuserauth.STATUS
     *
     * @param status the value for t_sysuserauth.STATUS
     *
     * @mbggenerated Thu Jun 04 14:54:12 CST 2015
     */
    public void setStatus(Byte status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sysuserauth.COLUMN1
     *
     * @return the value of t_sysuserauth.COLUMN1
     *
     * @mbggenerated Thu Jun 04 14:54:12 CST 2015
     */
    public String getColumn1() {
        return column1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sysuserauth.COLUMN1
     *
     * @param column1 the value for t_sysuserauth.COLUMN1
     *
     * @mbggenerated Thu Jun 04 14:54:12 CST 2015
     */
    public void setColumn1(String column1) {
        this.column1 = column1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sysuserauth.COLUMN2
     *
     * @return the value of t_sysuserauth.COLUMN2
     *
     * @mbggenerated Thu Jun 04 14:54:12 CST 2015
     */
    public String getColumn2() {
        return column2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sysuserauth.COLUMN2
     *
     * @param column2 the value for t_sysuserauth.COLUMN2
     *
     * @mbggenerated Thu Jun 04 14:54:12 CST 2015
     */
    public void setColumn2(String column2) {
        this.column2 = column2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sysuserauth.COLUMN3
     *
     * @return the value of t_sysuserauth.COLUMN3
     *
     * @mbggenerated Thu Jun 04 14:54:12 CST 2015
     */
    public String getColumn3() {
        return column3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sysuserauth.COLUMN3
     *
     * @param column3 the value for t_sysuserauth.COLUMN3
     *
     * @mbggenerated Thu Jun 04 14:54:12 CST 2015
     */
    public void setColumn3(String column3) {
        this.column3 = column3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sysuserauth.COLUMN4
     *
     * @return the value of t_sysuserauth.COLUMN4
     *
     * @mbggenerated Thu Jun 04 14:54:12 CST 2015
     */
    public String getColumn4() {
        return column4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sysuserauth.COLUMN4
     *
     * @param column4 the value for t_sysuserauth.COLUMN4
     *
     * @mbggenerated Thu Jun 04 14:54:12 CST 2015
     */
    public void setColumn4(String column4) {
        this.column4 = column4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sysuserauth.COLUMN5
     *
     * @return the value of t_sysuserauth.COLUMN5
     *
     * @mbggenerated Thu Jun 04 14:54:12 CST 2015
     */
    public String getColumn5() {
        return column5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sysuserauth.COLUMN5
     *
     * @param column5 the value for t_sysuserauth.COLUMN5
     *
     * @mbggenerated Thu Jun 04 14:54:12 CST 2015
     */
    public void setColumn5(String column5) {
        this.column5 = column5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sysuserauth.CREATEUSER
     *
     * @return the value of t_sysuserauth.CREATEUSER
     *
     * @mbggenerated Thu Jun 04 14:54:12 CST 2015
     */
    public Long getCreateuser() {
        return createuser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sysuserauth.CREATEUSER
     *
     * @param createuser the value for t_sysuserauth.CREATEUSER
     *
     * @mbggenerated Thu Jun 04 14:54:12 CST 2015
     */
    public void setCreateuser(Long createuser) {
        this.createuser = createuser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sysuserauth.CREATETIME
     *
     * @return the value of t_sysuserauth.CREATETIME
     *
     * @mbggenerated Thu Jun 04 14:54:12 CST 2015
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sysuserauth.CREATETIME
     *
     * @param createtime the value for t_sysuserauth.CREATETIME
     *
     * @mbggenerated Thu Jun 04 14:54:12 CST 2015
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sysuserauth.UPDATERCODE
     *
     * @return the value of t_sysuserauth.UPDATERCODE
     *
     * @mbggenerated Thu Jun 04 14:54:12 CST 2015
     */
    public Long getUpdatercode() {
        return updatercode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sysuserauth.UPDATERCODE
     *
     * @param updatercode the value for t_sysuserauth.UPDATERCODE
     *
     * @mbggenerated Thu Jun 04 14:54:12 CST 2015
     */
    public void setUpdatercode(Long updatercode) {
        this.updatercode = updatercode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sysuserauth.MODIFYTIME
     *
     * @return the value of t_sysuserauth.MODIFYTIME
     *
     * @mbggenerated Thu Jun 04 14:54:12 CST 2015
     */
    public Date getModifytime() {
        return modifytime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sysuserauth.MODIFYTIME
     *
     * @param modifytime the value for t_sysuserauth.MODIFYTIME
     *
     * @mbggenerated Thu Jun 04 14:54:12 CST 2015
     */
    public void setModifytime(Date modifytime) {
        this.modifytime = modifytime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sysuserauth.VALID
     *
     * @return the value of t_sysuserauth.VALID
     *
     * @mbggenerated Thu Jun 04 14:54:12 CST 2015
     */
    public Byte getValid() {
        return valid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sysuserauth.VALID
     *
     * @param valid the value for t_sysuserauth.VALID
     *
     * @mbggenerated Thu Jun 04 14:54:12 CST 2015
     */
    public void setValid(Byte valid) {
        this.valid = valid;
    }
}