package com.yousoft.model.security;

import java.util.Date;

public class TSysdepart {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sysdepart.DEPTID
     *
     * @mbggenerated Tue Jun 02 21:20:20 CST 2015
     */
    private Integer deptid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sysdepart.DEPTNAME
     *
     * @mbggenerated Tue Jun 02 21:20:20 CST 2015
     */
    private String deptname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sysdepart.UPPERDEPTID
     *
     * @mbggenerated Tue Jun 02 21:20:20 CST 2015
     */
    private Long upperdeptid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sysdepart.DEPTPATH
     *
     * @mbggenerated Tue Jun 02 21:20:20 CST 2015
     */
    private String deptpath;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sysdepart.COLUMN1
     *
     * @mbggenerated Tue Jun 02 21:20:20 CST 2015
     */
    private String column1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sysdepart.COLUMN2
     *
     * @mbggenerated Tue Jun 02 21:20:20 CST 2015
     */
    private String column2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sysdepart.COLUMN3
     *
     * @mbggenerated Tue Jun 02 21:20:20 CST 2015
     */
    private String column3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sysdepart.COLUMN4
     *
     * @mbggenerated Tue Jun 02 21:20:20 CST 2015
     */
    private String column4;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sysdepart.COLUMN5
     *
     * @mbggenerated Tue Jun 02 21:20:20 CST 2015
     */
    private String column5;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sysdepart.CREATEUSER
     *
     * @mbggenerated Tue Jun 02 21:20:20 CST 2015
     */
    private Long createuser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sysdepart.CREATETIME
     *
     * @mbggenerated Tue Jun 02 21:20:20 CST 2015
     */
    private Date createtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sysdepart.UPDATERCODE
     *
     * @mbggenerated Tue Jun 02 21:20:20 CST 2015
     */
    private Long updatercode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sysdepart.MODIFYTIME
     *
     * @mbggenerated Tue Jun 02 21:20:20 CST 2015
     */
    private Date modifytime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sysdepart.VALID
     *
     * @mbggenerated Tue Jun 02 21:20:20 CST 2015
     */
    private Byte valid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sysdepart.DEPTID
     *
     * @return the value of t_sysdepart.DEPTID
     *
     * @mbggenerated Tue Jun 02 21:20:20 CST 2015
     */
    public Integer getDeptid() {
        return deptid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sysdepart.DEPTID
     *
     * @param deptid the value for t_sysdepart.DEPTID
     *
     * @mbggenerated Tue Jun 02 21:20:20 CST 2015
     */
    public void setDeptid(Integer deptid) {
        this.deptid = deptid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sysdepart.DEPTNAME
     *
     * @return the value of t_sysdepart.DEPTNAME
     *
     * @mbggenerated Tue Jun 02 21:20:20 CST 2015
     */
    public String getDeptname() {
        return deptname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sysdepart.DEPTNAME
     *
     * @param deptname the value for t_sysdepart.DEPTNAME
     *
     * @mbggenerated Tue Jun 02 21:20:20 CST 2015
     */
    public void setDeptname(String deptname) {
        this.deptname = deptname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sysdepart.UPPERDEPTID
     *
     * @return the value of t_sysdepart.UPPERDEPTID
     *
     * @mbggenerated Tue Jun 02 21:20:20 CST 2015
     */
    public Long getUpperdeptid() {
        return upperdeptid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sysdepart.UPPERDEPTID
     *
     * @param upperdeptid the value for t_sysdepart.UPPERDEPTID
     *
     * @mbggenerated Tue Jun 02 21:20:20 CST 2015
     */
    public void setUpperdeptid(Long upperdeptid) {
        this.upperdeptid = upperdeptid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sysdepart.DEPTPATH
     *
     * @return the value of t_sysdepart.DEPTPATH
     *
     * @mbggenerated Tue Jun 02 21:20:20 CST 2015
     */
    public String getDeptpath() {
        return deptpath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sysdepart.DEPTPATH
     *
     * @param deptpath the value for t_sysdepart.DEPTPATH
     *
     * @mbggenerated Tue Jun 02 21:20:20 CST 2015
     */
    public void setDeptpath(String deptpath) {
        this.deptpath = deptpath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sysdepart.COLUMN1
     *
     * @return the value of t_sysdepart.COLUMN1
     *
     * @mbggenerated Tue Jun 02 21:20:20 CST 2015
     */
    public String getColumn1() {
        return column1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sysdepart.COLUMN1
     *
     * @param column1 the value for t_sysdepart.COLUMN1
     *
     * @mbggenerated Tue Jun 02 21:20:20 CST 2015
     */
    public void setColumn1(String column1) {
        this.column1 = column1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sysdepart.COLUMN2
     *
     * @return the value of t_sysdepart.COLUMN2
     *
     * @mbggenerated Tue Jun 02 21:20:20 CST 2015
     */
    public String getColumn2() {
        return column2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sysdepart.COLUMN2
     *
     * @param column2 the value for t_sysdepart.COLUMN2
     *
     * @mbggenerated Tue Jun 02 21:20:20 CST 2015
     */
    public void setColumn2(String column2) {
        this.column2 = column2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sysdepart.COLUMN3
     *
     * @return the value of t_sysdepart.COLUMN3
     *
     * @mbggenerated Tue Jun 02 21:20:20 CST 2015
     */
    public String getColumn3() {
        return column3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sysdepart.COLUMN3
     *
     * @param column3 the value for t_sysdepart.COLUMN3
     *
     * @mbggenerated Tue Jun 02 21:20:20 CST 2015
     */
    public void setColumn3(String column3) {
        this.column3 = column3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sysdepart.COLUMN4
     *
     * @return the value of t_sysdepart.COLUMN4
     *
     * @mbggenerated Tue Jun 02 21:20:20 CST 2015
     */
    public String getColumn4() {
        return column4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sysdepart.COLUMN4
     *
     * @param column4 the value for t_sysdepart.COLUMN4
     *
     * @mbggenerated Tue Jun 02 21:20:20 CST 2015
     */
    public void setColumn4(String column4) {
        this.column4 = column4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sysdepart.COLUMN5
     *
     * @return the value of t_sysdepart.COLUMN5
     *
     * @mbggenerated Tue Jun 02 21:20:20 CST 2015
     */
    public String getColumn5() {
        return column5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sysdepart.COLUMN5
     *
     * @param column5 the value for t_sysdepart.COLUMN5
     *
     * @mbggenerated Tue Jun 02 21:20:20 CST 2015
     */
    public void setColumn5(String column5) {
        this.column5 = column5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sysdepart.CREATEUSER
     *
     * @return the value of t_sysdepart.CREATEUSER
     *
     * @mbggenerated Tue Jun 02 21:20:20 CST 2015
     */
    public Long getCreateuser() {
        return createuser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sysdepart.CREATEUSER
     *
     * @param createuser the value for t_sysdepart.CREATEUSER
     *
     * @mbggenerated Tue Jun 02 21:20:20 CST 2015
     */
    public void setCreateuser(Long createuser) {
        this.createuser = createuser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sysdepart.CREATETIME
     *
     * @return the value of t_sysdepart.CREATETIME
     *
     * @mbggenerated Tue Jun 02 21:20:20 CST 2015
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sysdepart.CREATETIME
     *
     * @param createtime the value for t_sysdepart.CREATETIME
     *
     * @mbggenerated Tue Jun 02 21:20:20 CST 2015
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sysdepart.UPDATERCODE
     *
     * @return the value of t_sysdepart.UPDATERCODE
     *
     * @mbggenerated Tue Jun 02 21:20:20 CST 2015
     */
    public Long getUpdatercode() {
        return updatercode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sysdepart.UPDATERCODE
     *
     * @param updatercode the value for t_sysdepart.UPDATERCODE
     *
     * @mbggenerated Tue Jun 02 21:20:20 CST 2015
     */
    public void setUpdatercode(Long updatercode) {
        this.updatercode = updatercode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sysdepart.MODIFYTIME
     *
     * @return the value of t_sysdepart.MODIFYTIME
     *
     * @mbggenerated Tue Jun 02 21:20:20 CST 2015
     */
    public Date getModifytime() {
        return modifytime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sysdepart.MODIFYTIME
     *
     * @param modifytime the value for t_sysdepart.MODIFYTIME
     *
     * @mbggenerated Tue Jun 02 21:20:20 CST 2015
     */
    public void setModifytime(Date modifytime) {
        this.modifytime = modifytime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sysdepart.VALID
     *
     * @return the value of t_sysdepart.VALID
     *
     * @mbggenerated Tue Jun 02 21:20:20 CST 2015
     */
    public Byte getValid() {
        return valid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sysdepart.VALID
     *
     * @param valid the value for t_sysdepart.VALID
     *
     * @mbggenerated Tue Jun 02 21:20:20 CST 2015
     */
    public void setValid(Byte valid) {
        this.valid = valid;
    }
}