package com.yousoft.model.security;

import java.util.Date;

public class TSysmenu {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sysmenu.MENUID
     *
     * @mbggenerated Fri Jun 19 18:03:33 CST 2015
     */
    private Integer menuid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sysmenu.MENUNAME
     *
     * @mbggenerated Fri Jun 19 18:03:33 CST 2015
     */
    private String menuname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sysmenu.MENUURL
     *
     * @mbggenerated Fri Jun 19 18:03:33 CST 2015
     */
    private String menuurl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sysmenu.ICON
     *
     * @mbggenerated Fri Jun 19 18:03:33 CST 2015
     */
    private String icon;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sysmenu.UPPERMENUID
     *
     * @mbggenerated Fri Jun 19 18:03:33 CST 2015
     */
    private Integer uppermenuid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sysmenu.MENUIDX
     *
     * @mbggenerated Fri Jun 19 18:03:33 CST 2015
     */
    private Integer menuidx;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sysmenu.COLUMN1
     *
     * @mbggenerated Fri Jun 19 18:03:33 CST 2015
     */
    private String column1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sysmenu.COLUMN2
     *
     * @mbggenerated Fri Jun 19 18:03:33 CST 2015
     */
    private String column2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sysmenu.COLUMN3
     *
     * @mbggenerated Fri Jun 19 18:03:33 CST 2015
     */
    private String column3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sysmenu.CREATEUSER
     *
     * @mbggenerated Fri Jun 19 18:03:33 CST 2015
     */
    private Long createuser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sysmenu.CREATETIME
     *
     * @mbggenerated Fri Jun 19 18:03:33 CST 2015
     */
    private Date createtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sysmenu.UPDATERCODE
     *
     * @mbggenerated Fri Jun 19 18:03:33 CST 2015
     */
    private Long updatercode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sysmenu.MODIFYTIME
     *
     * @mbggenerated Fri Jun 19 18:03:33 CST 2015
     */
    private Date modifytime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sysmenu.VALID
     *
     * @mbggenerated Fri Jun 19 18:03:33 CST 2015
     */
    private Byte valid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sysmenu.MENUID
     *
     * @return the value of t_sysmenu.MENUID
     *
     * @mbggenerated Fri Jun 19 18:03:33 CST 2015
     */
    public Integer getMenuid() {
        return menuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sysmenu.MENUID
     *
     * @param menuid the value for t_sysmenu.MENUID
     *
     * @mbggenerated Fri Jun 19 18:03:33 CST 2015
     */
    public void setMenuid(Integer menuid) {
        this.menuid = menuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sysmenu.MENUNAME
     *
     * @return the value of t_sysmenu.MENUNAME
     *
     * @mbggenerated Fri Jun 19 18:03:33 CST 2015
     */
    public String getMenuname() {
        return menuname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sysmenu.MENUNAME
     *
     * @param menuname the value for t_sysmenu.MENUNAME
     *
     * @mbggenerated Fri Jun 19 18:03:33 CST 2015
     */
    public void setMenuname(String menuname) {
        this.menuname = menuname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sysmenu.MENUURL
     *
     * @return the value of t_sysmenu.MENUURL
     *
     * @mbggenerated Fri Jun 19 18:03:33 CST 2015
     */
    public String getMenuurl() {
        return menuurl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sysmenu.MENUURL
     *
     * @param menuurl the value for t_sysmenu.MENUURL
     *
     * @mbggenerated Fri Jun 19 18:03:33 CST 2015
     */
    public void setMenuurl(String menuurl) {
        this.menuurl = menuurl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sysmenu.ICON
     *
     * @return the value of t_sysmenu.ICON
     *
     * @mbggenerated Fri Jun 19 18:03:33 CST 2015
     */
    public String getIcon() {
        return icon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sysmenu.ICON
     *
     * @param icon the value for t_sysmenu.ICON
     *
     * @mbggenerated Fri Jun 19 18:03:33 CST 2015
     */
    public void setIcon(String icon) {
        this.icon = icon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sysmenu.UPPERMENUID
     *
     * @return the value of t_sysmenu.UPPERMENUID
     *
     * @mbggenerated Fri Jun 19 18:03:33 CST 2015
     */
    public Integer getUppermenuid() {
        return uppermenuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sysmenu.UPPERMENUID
     *
     * @param uppermenuid the value for t_sysmenu.UPPERMENUID
     *
     * @mbggenerated Fri Jun 19 18:03:33 CST 2015
     */
    public void setUppermenuid(Integer uppermenuid) {
        this.uppermenuid = uppermenuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sysmenu.MENUIDX
     *
     * @return the value of t_sysmenu.MENUIDX
     *
     * @mbggenerated Fri Jun 19 18:03:33 CST 2015
     */
    public Integer getMenuidx() {
        return menuidx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sysmenu.MENUIDX
     *
     * @param menuidx the value for t_sysmenu.MENUIDX
     *
     * @mbggenerated Fri Jun 19 18:03:33 CST 2015
     */
    public void setMenuidx(Integer menuidx) {
        this.menuidx = menuidx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sysmenu.COLUMN1
     *
     * @return the value of t_sysmenu.COLUMN1
     *
     * @mbggenerated Fri Jun 19 18:03:33 CST 2015
     */
    public String getColumn1() {
        return column1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sysmenu.COLUMN1
     *
     * @param column1 the value for t_sysmenu.COLUMN1
     *
     * @mbggenerated Fri Jun 19 18:03:33 CST 2015
     */
    public void setColumn1(String column1) {
        this.column1 = column1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sysmenu.COLUMN2
     *
     * @return the value of t_sysmenu.COLUMN2
     *
     * @mbggenerated Fri Jun 19 18:03:33 CST 2015
     */
    public String getColumn2() {
        return column2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sysmenu.COLUMN2
     *
     * @param column2 the value for t_sysmenu.COLUMN2
     *
     * @mbggenerated Fri Jun 19 18:03:33 CST 2015
     */
    public void setColumn2(String column2) {
        this.column2 = column2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sysmenu.COLUMN3
     *
     * @return the value of t_sysmenu.COLUMN3
     *
     * @mbggenerated Fri Jun 19 18:03:33 CST 2015
     */
    public String getColumn3() {
        return column3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sysmenu.COLUMN3
     *
     * @param column3 the value for t_sysmenu.COLUMN3
     *
     * @mbggenerated Fri Jun 19 18:03:33 CST 2015
     */
    public void setColumn3(String column3) {
        this.column3 = column3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sysmenu.CREATEUSER
     *
     * @return the value of t_sysmenu.CREATEUSER
     *
     * @mbggenerated Fri Jun 19 18:03:33 CST 2015
     */
    public Long getCreateuser() {
        return createuser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sysmenu.CREATEUSER
     *
     * @param createuser the value for t_sysmenu.CREATEUSER
     *
     * @mbggenerated Fri Jun 19 18:03:33 CST 2015
     */
    public void setCreateuser(Long createuser) {
        this.createuser = createuser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sysmenu.CREATETIME
     *
     * @return the value of t_sysmenu.CREATETIME
     *
     * @mbggenerated Fri Jun 19 18:03:33 CST 2015
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sysmenu.CREATETIME
     *
     * @param createtime the value for t_sysmenu.CREATETIME
     *
     * @mbggenerated Fri Jun 19 18:03:33 CST 2015
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sysmenu.UPDATERCODE
     *
     * @return the value of t_sysmenu.UPDATERCODE
     *
     * @mbggenerated Fri Jun 19 18:03:33 CST 2015
     */
    public Long getUpdatercode() {
        return updatercode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sysmenu.UPDATERCODE
     *
     * @param updatercode the value for t_sysmenu.UPDATERCODE
     *
     * @mbggenerated Fri Jun 19 18:03:33 CST 2015
     */
    public void setUpdatercode(Long updatercode) {
        this.updatercode = updatercode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sysmenu.MODIFYTIME
     *
     * @return the value of t_sysmenu.MODIFYTIME
     *
     * @mbggenerated Fri Jun 19 18:03:33 CST 2015
     */
    public Date getModifytime() {
        return modifytime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sysmenu.MODIFYTIME
     *
     * @param modifytime the value for t_sysmenu.MODIFYTIME
     *
     * @mbggenerated Fri Jun 19 18:03:33 CST 2015
     */
    public void setModifytime(Date modifytime) {
        this.modifytime = modifytime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sysmenu.VALID
     *
     * @return the value of t_sysmenu.VALID
     *
     * @mbggenerated Fri Jun 19 18:03:33 CST 2015
     */
    public Byte getValid() {
        return valid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sysmenu.VALID
     *
     * @param valid the value for t_sysmenu.VALID
     *
     * @mbggenerated Fri Jun 19 18:03:33 CST 2015
     */
    public void setValid(Byte valid) {
        this.valid = valid;
    }
}