package com.yousoft.client.security;

import com.yousoft.model.security.TSysdepart;
import com.yousoft.model.security.TSysdepartExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

@Repository
public interface TSysdepartMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sysdepart
     *
     * @mbggenerated Tue Jun 02 21:20:20 CST 2015
     */
    int countByExample(TSysdepartExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sysdepart
     *
     * @mbggenerated Tue Jun 02 21:20:20 CST 2015
     */
    int deleteByExample(TSysdepartExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sysdepart
     *
     * @mbggenerated Tue Jun 02 21:20:20 CST 2015
     */
    int deleteByPrimaryKey(Integer deptid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sysdepart
     *
     * @mbggenerated Tue Jun 02 21:20:20 CST 2015
     */
    int insert(TSysdepart record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sysdepart
     *
     * @mbggenerated Tue Jun 02 21:20:20 CST 2015
     */
    int insertSelective(TSysdepart record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sysdepart
     *
     * @mbggenerated Tue Jun 02 21:20:20 CST 2015
     */
    List<TSysdepart> selectByExample(TSysdepartExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sysdepart
     *
     * @mbggenerated Tue Jun 02 21:20:20 CST 2015
     */
    TSysdepart selectByPrimaryKey(Integer deptid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sysdepart
     *
     * @mbggenerated Tue Jun 02 21:20:20 CST 2015
     */
    int updateByExampleSelective(@Param("record") TSysdepart record, @Param("example") TSysdepartExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sysdepart
     *
     * @mbggenerated Tue Jun 02 21:20:20 CST 2015
     */
    int updateByExample(@Param("record") TSysdepart record, @Param("example") TSysdepartExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sysdepart
     *
     * @mbggenerated Tue Jun 02 21:20:20 CST 2015
     */
    int updateByPrimaryKeySelective(TSysdepart record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sysdepart
     *
     * @mbggenerated Tue Jun 02 21:20:20 CST 2015
     */
    int updateByPrimaryKey(TSysdepart record);
}