package com.yousoft.client.security;

import java.util.List;

import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

import com.yousoft.model.security.TSysresources;
import com.yousoft.model.security.TSysresourcesExample;
import com.yousoft.model.security.view.ResRoleModel;

@Repository
public interface TSysresourcesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sysresources
     *
     * @mbggenerated Tue Jun 02 21:20:20 CST 2015
     */
    int countByExample(TSysresourcesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sysresources
     *
     * @mbggenerated Tue Jun 02 21:20:20 CST 2015
     */
    int deleteByExample(TSysresourcesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sysresources
     *
     * @mbggenerated Tue Jun 02 21:20:20 CST 2015
     */
    int deleteByPrimaryKey(Integer resid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sysresources
     *
     * @mbggenerated Tue Jun 02 21:20:20 CST 2015
     */
    int insert(TSysresources record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sysresources
     *
     * @mbggenerated Tue Jun 02 21:20:20 CST 2015
     */
    int insertSelective(TSysresources record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sysresources
     *
     * @mbggenerated Tue Jun 02 21:20:20 CST 2015
     */
    List<TSysresources> selectByExample(TSysresourcesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sysresources
     *
     * @mbggenerated Tue Jun 02 21:20:20 CST 2015
     */
    TSysresources selectByPrimaryKey(Integer resid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sysresources
     *
     * @mbggenerated Tue Jun 02 21:20:20 CST 2015
     */
    int updateByExampleSelective(@Param("record") TSysresources record, @Param("example") TSysresourcesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sysresources
     *
     * @mbggenerated Tue Jun 02 21:20:20 CST 2015
     */
    int updateByExample(@Param("record") TSysresources record, @Param("example") TSysresourcesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sysresources
     *
     * @mbggenerated Tue Jun 02 21:20:20 CST 2015
     */
    int updateByPrimaryKeySelective(TSysresources record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sysresources
     *
     * @mbggenerated Tue Jun 02 21:20:20 CST 2015
     */
    int updateByPrimaryKey(TSysresources record);
    
}