package com.yousoft.client.security;

import com.yousoft.model.security.TSysmenu;
import com.yousoft.model.security.TSysmenuExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TSysmenuMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sysmenu
     *
     * @mbggenerated Fri Jun 19 18:03:33 CST 2015
     */
    int countByExample(TSysmenuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sysmenu
     *
     * @mbggenerated Fri Jun 19 18:03:33 CST 2015
     */
    int deleteByExample(TSysmenuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sysmenu
     *
     * @mbggenerated Fri Jun 19 18:03:33 CST 2015
     */
    int deleteByPrimaryKey(Integer menuid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sysmenu
     *
     * @mbggenerated Fri Jun 19 18:03:33 CST 2015
     */
    int insert(TSysmenu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sysmenu
     *
     * @mbggenerated Fri Jun 19 18:03:33 CST 2015
     */
    int insertSelective(TSysmenu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sysmenu
     *
     * @mbggenerated Fri Jun 19 18:03:33 CST 2015
     */
    List<TSysmenu> selectByExample(TSysmenuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sysmenu
     *
     * @mbggenerated Fri Jun 19 18:03:33 CST 2015
     */
    TSysmenu selectByPrimaryKey(Integer menuid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sysmenu
     *
     * @mbggenerated Fri Jun 19 18:03:33 CST 2015
     */
    int updateByExampleSelective(@Param("record") TSysmenu record, @Param("example") TSysmenuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sysmenu
     *
     * @mbggenerated Fri Jun 19 18:03:33 CST 2015
     */
    int updateByExample(@Param("record") TSysmenu record, @Param("example") TSysmenuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sysmenu
     *
     * @mbggenerated Fri Jun 19 18:03:33 CST 2015
     */
    int updateByPrimaryKeySelective(TSysmenu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sysmenu
     *
     * @mbggenerated Fri Jun 19 18:03:33 CST 2015
     */
    int updateByPrimaryKey(TSysmenu record);
}