package com.yousoft.client.security;

import com.yousoft.model.security.TSysuserrole;
import com.yousoft.model.security.TSysuserroleExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

@Repository
public interface TSysuserroleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sysuserrole
     *
     * @mbggenerated Tue Jun 02 21:20:20 CST 2015
     */
    int countByExample(TSysuserroleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sysuserrole
     *
     * @mbggenerated Tue Jun 02 21:20:20 CST 2015
     */
    int deleteByExample(TSysuserroleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sysuserrole
     *
     * @mbggenerated Tue Jun 02 21:20:20 CST 2015
     */
    int deleteByPrimaryKey(Integer urid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sysuserrole
     *
     * @mbggenerated Tue Jun 02 21:20:20 CST 2015
     */
    int insert(TSysuserrole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sysuserrole
     *
     * @mbggenerated Tue Jun 02 21:20:20 CST 2015
     */
    int insertSelective(TSysuserrole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sysuserrole
     *
     * @mbggenerated Tue Jun 02 21:20:20 CST 2015
     */
    List<TSysuserrole> selectByExample(TSysuserroleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sysuserrole
     *
     * @mbggenerated Tue Jun 02 21:20:20 CST 2015
     */
    TSysuserrole selectByPrimaryKey(Integer urid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sysuserrole
     *
     * @mbggenerated Tue Jun 02 21:20:20 CST 2015
     */
    int updateByExampleSelective(@Param("record") TSysuserrole record, @Param("example") TSysuserroleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sysuserrole
     *
     * @mbggenerated Tue Jun 02 21:20:20 CST 2015
     */
    int updateByExample(@Param("record") TSysuserrole record, @Param("example") TSysuserroleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sysuserrole
     *
     * @mbggenerated Tue Jun 02 21:20:20 CST 2015
     */
    int updateByPrimaryKeySelective(TSysuserrole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sysuserrole
     *
     * @mbggenerated Tue Jun 02 21:20:20 CST 2015
     */
    int updateByPrimaryKey(TSysuserrole record);
}