package com.yousoft.client.security;

import com.yousoft.model.security.TSysuser;
import com.yousoft.model.security.TSysuserExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

@Repository
public interface TSysuserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sysuser
     *
     * @mbggenerated Tue Jun 02 21:20:20 CST 2015
     */
    int countByExample(TSysuserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sysuser
     *
     * @mbggenerated Tue Jun 02 21:20:20 CST 2015
     */
    int deleteByExample(TSysuserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sysuser
     *
     * @mbggenerated Tue Jun 02 21:20:20 CST 2015
     */
    int deleteByPrimaryKey(Long userid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sysuser
     *
     * @mbggenerated Tue Jun 02 21:20:20 CST 2015
     */
    int insert(TSysuser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sysuser
     *
     * @mbggenerated Tue Jun 02 21:20:20 CST 2015
     */
    int insertSelective(TSysuser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sysuser
     *
     * @mbggenerated Tue Jun 02 21:20:20 CST 2015
     */
    List<TSysuser> selectByExample(TSysuserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sysuser
     *
     * @mbggenerated Tue Jun 02 21:20:20 CST 2015
     */
    TSysuser selectByPrimaryKey(Long userid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sysuser
     *
     * @mbggenerated Tue Jun 02 21:20:20 CST 2015
     */
    int updateByExampleSelective(@Param("record") TSysuser record, @Param("example") TSysuserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sysuser
     *
     * @mbggenerated Tue Jun 02 21:20:20 CST 2015
     */
    int updateByExample(@Param("record") TSysuser record, @Param("example") TSysuserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sysuser
     *
     * @mbggenerated Tue Jun 02 21:20:20 CST 2015
     */
    int updateByPrimaryKeySelective(TSysuser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sysuser
     *
     * @mbggenerated Tue Jun 02 21:20:20 CST 2015
     */
    int updateByPrimaryKey(TSysuser record);
}