DROP DATABASE IF EXISTS ARCH;
CREATE DATABASE ARCH;

USE ARCH;

-- 部门信息表
DROP TABLE IF EXISTS T_SYSDEPART;
CREATE TABLE T_SYSDEPART(
	DEPTID INT AUTO_INCREMENT NOT NULL COMMENT '部门ID',
	DEPTNAME VARCHAR(500) NOT NULL COMMENT '部门名称',
	UPPERDEPTID BIGINT NOT NULL DEFAULT 0 COMMENT '上级部门ID',
	DEPTPATH VARCHAR(500) NOT NULL DEFAULT '0' COMMENT '部门上下级路径',
	COLUMN1 VARCHAR(200) DEFAULT NULL COMMENT '预留字段1',
	COLUMN2 VARCHAR(200) DEFAULT NULL COMMENT '预留字段2',
	COLUMN3 VARCHAR(200) DEFAULT NULL COMMENT '预留字段3',
	COLUMN4 VARCHAR(200) DEFAULT NULL COMMENT '预留字段4',
	COLUMN5 VARCHAR(200) DEFAULT NULL COMMENT '预留字段5',
	CREATEUSER BIGINT NOT NULL COMMENT '创建者ID',
	CREATETIME TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '记录创建时间',
	UPDATERCODE BIGINT DEFAULT NULL COMMENT '更新者ID',
	MODIFYTIME TIMESTAMP COMMENT '记录更新时间',
	VALID TINYINT DEFAULT 0 COMMENT '有效状态 0有效 1无效',
	PRIMARY KEY(DEPTID),
	KEY `SYSDEPART_DEPTID_IDX`(DEPTID),
	KEY `SYSDEPART_UPPERDEPTID_IDX`(UPPERDEPTID)
)ENGINE=INNODB AUTO_INCREMENT=10000 DEFAULT CHARSET=UTF8;
-- 插入测试数据
INSERT INTO T_SYSDEPART(DEPTNAME,UPPERDEPTID,DEPTPATH) VALUES ('总经理室',0,'0');

-- 系统用户信息表
DROP TABLE IF EXISTS T_SYSUSER;
CREATE TABLE T_SYSUSER(
	USERID BIGINT AUTO_INCREMENT NOT NULL COMMENT '用户ID',
	USERCODE VARCHAR(100) DEFAULT NULL COMMENT '用户代码',
	USERNAME VARCHAR(100) NOT NULL COMMENT '用户姓名',
	DEPARTID INT NOT NULL COMMENT '部门ID',
	EMAIL VARCHAR(100) DEFAULT NULL COMMENT '邮件地址',
	PHONENUMBER CHAR(20) DEFAULT NULL COMMENT '手机号码',
	COLUMN1 VARCHAR(200) DEFAULT NULL COMMENT '预留字段1',
	COLUMN2 VARCHAR(200) DEFAULT NULL COMMENT '预留字段2',
	COLUMN3 VARCHAR(200) DEFAULT NULL COMMENT '预留字段3',
	COLUMN4 VARCHAR(200) DEFAULT NULL COMMENT '预留字段4',
	COLUMN5 VARCHAR(200) DEFAULT NULL COMMENT '预留字段5',
	CREATEUSER BIGINT NOT NULL COMMENT '创建者ID',
	CREATETIME TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '记录创建时间',
	UPDATERCODE BIGINT DEFAULT NULL COMMENT '更新者ID',
	MODIFYTIME TIMESTAMP COMMENT '记录更新时间',
	VALID TINYINT DEFAULT 0 COMMENT '有效状态 0有效 1无效',
	PRIMARY KEY(USERID),
	KEY `SYSUSER_DEPARTID_IDX`(DEPARTID),
	KEY `SYSUSER_USERCODE_IDX`(USERCODE)
)ENGINE=INNODB AUTO_INCREMENT=10000000 DEFAULT CHARSET=UTF8;

INSERT INTO T_SYSUSER(USERNAME,DEPARTID) VALUES ('张三',10000);

-- 系统用户验证信息表
DROP TABLE IF EXISTS T_SYSUSERAUTH;
CREATE TABLE T_SYSUSERAUTH(
	AUID BIGINT AUTO_INCREMENT NOT NULL COMMENT '验证自增ID',
	USERID BIGINT NOT NULL COMMENT '用户ID',
	LOGINCODE VARCHAR(100) UNIQUE DEFAULT NULL COMMENT '登录代码',
	PASSWORD VARCHAR(255) DEFAULT NULL COMMENT '用户登录密码(DES加密)',
	STATUS TINYINT DEFAULT 0 COMMENT '帐号状态 0正常 1账号锁定 2账号过期 3异常登录',
	COLUMN1 VARCHAR(200) DEFAULT NULL COMMENT '预留字段1',
	COLUMN2 VARCHAR(200) DEFAULT NULL COMMENT '预留字段2',
	COLUMN3 VARCHAR(200) DEFAULT NULL COMMENT '预留字段3',
	COLUMN4 VARCHAR(200) DEFAULT NULL COMMENT '预留字段4',
	COLUMN5 VARCHAR(200) DEFAULT NULL COMMENT '预留字段5',
	CREATEUSER BIGINT NOT NULL COMMENT '创建者ID',
	CREATETIME TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '记录创建时间',
	UPDATERCODE BIGINT DEFAULT NULL COMMENT '更新者ID',
	MODIFYTIME TIMESTAMP COMMENT '记录更新时间',
	VALID TINYINT DEFAULT 0 COMMENT '有效状态 0有效 1无效',
	PRIMARY KEY(AUID),
	KEY `SYSUSERAUTH_USERID_IDX`(USERID),
	KEY `SYSUSERAUTH_LOGINCODE_IDX`(LOGINCODE)
)ENGINE=INNODB DEFAULT CHARSET=UTF8;
-- 添加测试数据
INSERT INTO T_SYSUSERAUTH(USERID,LOGINCODE,PASSWORD) VALUES (10000000,'admin','21232F297A57A5A743894A0E4A801FC3');

-- 系统角色信息表
DROP TABLE IF EXISTS T_SYSROLE;
CREATE TABLE T_SYSROLE(
	ROLEID INT AUTO_INCREMENT NOT NULL COMMENT '角色自增ID',
	ROLENAME VARCHAR(100) NOT NULL COMMENT '角色名称',
	COLUMN1 VARCHAR(200) DEFAULT NULL COMMENT '预留字段1',
	COLUMN2 VARCHAR(200) DEFAULT NULL COMMENT '预留字段2',
	COLUMN3 VARCHAR(200) DEFAULT NULL COMMENT '预留字段3',
	CREATEUSER BIGINT NOT NULL COMMENT '创建者ID',
	CREATETIME TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '记录创建时间',
	UPDATERCODE BIGINT DEFAULT NULL COMMENT '更新者ID',
	MODIFYTIME TIMESTAMP COMMENT '记录更新时间',
	VALID TINYINT DEFAULT 0 COMMENT '有效状态 0有效 1无效',
	PRIMARY KEY(ROLEID),
	KEY `SYSROLE_ROLENAME_IDX`(ROLENAME)
)ENGINE=INNODB DEFAULT CHARSET=UTF8;
-- 添加测试数据
INSERT INTO T_SYSROLE(ROLENAME) VALUES ('系统管理员');

-- 用户角色关联信息表
DROP TABLE IF EXISTS T_SYSUSERROLE;
CREATE TABLE T_SYSUSERROLE(
	URID BIGINT AUTO_INCREMENT NOT NULL COMMENT '用户角色自增ID',
	USERID BIGINT NOT NULL COMMENT '用户ID',
	ROLEID INT NOT NULL COMMENT '角色ID',
	COLUMN1 VARCHAR(200) DEFAULT NULL COMMENT '预留字段1',
	COLUMN2 VARCHAR(200) DEFAULT NULL COMMENT '预留字段2',
	COLUMN3 VARCHAR(200) DEFAULT NULL COMMENT '预留字段3',
	CREATEUSER BIGINT NOT NULL COMMENT '创建者ID',
	CREATETIME TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '记录创建时间',
	UPDATERCODE BIGINT DEFAULT NULL COMMENT '更新者ID',
	MODIFYTIME TIMESTAMP COMMENT '记录更新时间',
	VALID TINYINT DEFAULT 0 COMMENT '有效状态 0有效 1无效',
	PRIMARY KEY(URID),
	KEY `SYSUSERROLE_USERID_IDX`(USERID),
	KEY `SYSUSERROLE_ROLEID_IDX`(ROLEID)
)ENGINE=INNODB DEFAULT CHARSET=UTF8;
-- 插入测试数据
INSERT INTO T_SYSUSERROLE(USERID,ROLEID) VALUES (10000000,1);

-- 系统访问资源信息表
DROP TABLE IF EXISTS T_SYSRESOURCES;
CREATE TABLE T_SYSRESOURCES(
	RESID INT AUTO_INCREMENT NOT NULL COMMENT '资源ID',
	RESNAME VARCHAR(100) NOT NULL COMMENT '资源名称',
	RESURL VARCHAR(500) DEFAULT NULL COMMENT '访问资源URL',
	COLUMN1 VARCHAR(200) DEFAULT NULL COMMENT '预留字段1',
	COLUMN2 VARCHAR(200) DEFAULT NULL COMMENT '预留字段2',
	COLUMN3 VARCHAR(200) DEFAULT NULL COMMENT '预留字段3',
	CREATEUSER BIGINT NOT NULL COMMENT '创建者ID',
	CREATETIME TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '记录创建时间',
	UPDATERCODE BIGINT DEFAULT NULL COMMENT '更新者ID',
	MODIFYTIME TIMESTAMP COMMENT '记录更新时间',
	VALID TINYINT DEFAULT 0 COMMENT '有效状态 0有效 1无效',
	PRIMARY KEY(RESID),
	KEY `SYSRESOURCES_RESNAME_IDX`(RESNAME)
)ENGINE=INNODB DEFAULT CHARSET=UTF8;
-- 插入测试数据
INSERT INTO T_SYSRESOURCES(RESNAME,RESURL) VALUES ('系统首页','/main.jsp');

-- 系统角色资源关联信息表
DROP TABLE IF EXISTS T_SYSROLERESOURCE;
CREATE TABLE T_SYSROLERESOURCE(
	ROLERESID INT AUTO_INCREMENT NOT NULL COMMENT '角色资源ID',
	ROLEID INT NOT NULL COMMENT '角色ID',
	RESID INT NOT NULL COMMENT '资源ID',
	AUTHORITY INT NOT NULL DEFAULT 0 COMMENT '授权类型:0只读 1编辑 2删除',
	CREATEUSER BIGINT NOT NULL COMMENT '创建者ID',
	CREATETIME TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '记录创建时间',
	UPDATERCODE BIGINT DEFAULT NULL COMMENT '更新者ID',
	MODIFYTIME TIMESTAMP COMMENT '记录更新时间',
	VALID TINYINT DEFAULT 0 COMMENT '有效状态 0有效 1无效',
	PRIMARY KEY(ROLERESID),
	KEY `SYSROLERESOURCE_ROLEID_IDX`(ROLEID),
	KEY `SYSROLERESOURCE_RESID_IDX`(RESID)
)ENGINE=INNODB DEFAULT CHARSET=UTF8;
-- 插入测试数据
INSERT INTO T_SYSROLERESOURCE(ROLEID,RESID) VALUES (1,1);


-- 菜单信息表
DROP TABLE IF EXISTS T_SYSMENU;
CREATE TABLE T_SYSMENU(
	MENUID INT AUTO_INCREMENT NOT NULL COMMENT '菜单ID',
	MENUNAME VARCHAR(100) NOT NULL COMMENT '菜单名称',
	MENUURL VARCHAR(1000) DEFAULT '' COMMENT '菜单请求URL',
	ICON VARCHAR(50) DEFAULT '' COMMENT '菜单图标',
	UPPERMENUID INT NOT NULL DEFAULT 0 COMMENT '上级菜单ID',
	MENUIDX INT NOT NULL DEFAULT 0 COMMENT '菜单序号',
	COLUMN1 VARCHAR(200) DEFAULT NULL COMMENT '预留字段1',
	COLUMN2 VARCHAR(200) DEFAULT NULL COMMENT '预留字段2',
	COLUMN3 VARCHAR(200) DEFAULT NULL COMMENT '预留字段3',
	CREATEUSER BIGINT NOT NULL COMMENT '创建者ID',
	CREATETIME TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '记录创建时间',
	UPDATERCODE BIGINT DEFAULT NULL COMMENT '更新者ID',
	MODIFYTIME TIMESTAMP COMMENT '记录更新时间',
	VALID TINYINT DEFAULT 0 COMMENT '有效状态 0有效 1无效',
	PRIMARY KEY(MENUID),
	KEY `SYSMENU_UPPERMENUID_IDX`(UPPERMENUID)
)ENGINE=INNODB DEFAULT CHARSET=UTF8;

-- 插入测试数据
INSERT INTO T_SYSMENU(MENUNAME,MENUIDX) VALUES ('流程管理',1);
INSERT INTO T_SYSMENU(MENUNAME,MENUIDX) VALUES ('微信管理',2);
INSERT INTO T_SYSMENU(MENUNAME,MENUIDX) VALUES ('报表管理',3);
INSERT INTO T_SYSMENU(MENUNAME,MENUIDX) VALUES ('系统管理',4);
INSERT INTO T_SYSMENU(MENUNAME,MENUIDX,UPPERMENUID) VALUES ('我发起的流程',1,1);
INSERT INTO T_SYSMENU(MENUNAME,MENUIDX,UPPERMENUID) VALUES ('待处理流程',2,1);
INSERT INTO T_SYSMENU(MENUNAME,MENUIDX,UPPERMENUID) VALUES ('历史流程',3,1);
INSERT INTO T_SYSMENU(MENUNAME,MENUIDX,UPPERMENUID) VALUES ('发布流程',4,1);
INSERT INTO T_SYSMENU(MENUNAME,MENUIDX,UPPERMENUID) VALUES ('流程维护',5,1);


INSERT INTO T_SYSMENU(MENUNAME,MENUIDX,UPPERMENUID) VALUES ('菜单管理',1,2);
INSERT INTO T_SYSMENU(MENUNAME,MENUIDX,UPPERMENUID) VALUES ('接口维护',2,2);
INSERT INTO T_SYSMENU(MENUNAME,MENUIDX,UPPERMENUID) VALUES ('微信会话',3,2);
INSERT INTO T_SYSMENU(MENUNAME,MENUIDX,UPPERMENUID) VALUES ('素材管理',4,2);
INSERT INTO T_SYSMENU(MENUNAME,MENUIDX,UPPERMENUID) VALUES ('会员卡管理',5,2);


INSERT INTO T_SYSMENU(MENUNAME,MENUIDX,UPPERMENUID) VALUES ('我的报表',1,3);
INSERT INTO T_SYSMENU(MENUNAME,MENUIDX,UPPERMENUID) VALUES ('报表库查询',2,3);
INSERT INTO T_SYSMENU(MENUNAME,MENUIDX,UPPERMENUID) VALUES ('报表配置',3,3);
INSERT INTO T_SYSMENU(MENUNAME,MENUIDX,UPPERMENUID) VALUES ('报表发布',4,3);


INSERT INTO T_SYSMENU(MENUNAME,MENUIDX,UPPERMENUID) VALUES ('用户管理',1,4);
INSERT INTO T_SYSMENU(MENUNAME,MENUIDX,UPPERMENUID) VALUES ('日志管理',2,4);
INSERT INTO T_SYSMENU(MENUNAME,MENUIDX,UPPERMENUID) VALUES ('服务管理',3,4);
INSERT INTO T_SYSMENU(MENUNAME,MENUIDX,UPPERMENUID) VALUES ('部门管理',4,4);
INSERT INTO T_SYSMENU(MENUNAME,MENUIDX,UPPERMENUID) VALUES ('菜单管理',5,4);

INSERT INTO T_SYSMENU(MENUNAME,MENUIDX,UPPERMENUID) VALUES ('用户添加',1,19);
INSERT INTO T_SYSMENU(MENUNAME,MENUIDX,UPPERMENUID) VALUES ('用户修改',1,19);
INSERT INTO T_SYSMENU(MENUNAME,MENUIDX,UPPERMENUID) VALUES ('用户删除',1,19);




